### ISSUE TITLE
Semantic Segmentation Code Release

### ISSUE THREAD

**Issue by mrclovvn** [NUS-HPC-AI-Lab/Dynamic-Tuning#1]
Hi,

Thank you for sharing your insightful work! I am interested in conducting comparison experiments based on your paper. However, I noticed that the semantic segmentation training codes have not been released. Could you kindly share the code to help reproduce the results from the paper?

Best regards,
Shawn

**Comment by wangbo-zhao** [comment]
Thank you for your interest. I will update the code along with the camera-ready version of the paper. I conduct the experiments based on https://github.com/czczup/ViT-Adapter/tree/main/segmentation and you can try this first (if you are urgent to do this). Thanks.

**Comment by mrclovvn** [comment]
Thanks for your response!
And I am wondering if the experimental results in the current arXiv version match those in the camera-ready version?

**Comment by wangbo-zhao** [comment]
Most are matched. We improve the performance of our model on VTAB-1K.

**Comment by mrclovvn** [comment]
I got it. Thanks again for your prompt response!
I am looking forward to the release of the camera-ready version.

**Comment by wangbo-zhao** [comment]
Thank you for your understanding.

**Comment by mrclovvn** [comment]
> Most are matched. We improve the performance of our model on VTAB-1K.

Could you kindly share the details on how VTAB-1K performance was improved compared to the current arXiv version? Specifically, I am interested in the training strategies, hyperparameters or data augmentations used in the camera-ready version. I plan to compare experimental performance with DyT and would like to adhere to the final settings for a fair comparison.

**Comment by wangbo-zhao** [comment]
We introduce the distillation technique into our VTAB-1K experiments, which improves the performance of DyT r = 0.5 to 77.14 on VTAB-1K. We also report the VTAb-1K reuslts of the current arXiv version.

In fact, I thinks that you can still compare your method with the reuslts of the current arXiv version, because the distillation technique  introduces extra computational cost.

**Comment by mrclovvn** [comment]
Many thanks for your help!

**Comment by wangbo-zhao** [comment]
The distillation teachnique and semantic segmentation have been added.
