### ISSUE TITLE
about Token Dispatcher

### ISSUE THREAD

**Issue by hpnquoc** [NUS-HPC-AI-Lab/Dynamic-Tuning#2]
First of all, thank you for your hard work.

I have a question about the dispatcher. Could you navigate the dispatcher for the inference part inside the code? because I can't find it anywhere

thank you very much!
![Screenshot from 2024-10-10 18-58-48](https://github.com/user-attachments/assets/877880cb-5000-4e63-bdff-a73f765fd231)

**Comment by wangbo-zhao** [comment]
Thanks you for your interest. I will update the code with the camera-ready version of the paper. You can first try use torch.gather and torch.scatter to achieve this based on the mask from dispatcher, which is my implementation.

**Comment by wangbo-zhao** [comment]
The inference code has been released.
